### ISSUE TITLE
반납 폼 데이터 조회 파라미터 에러 

### ISSUE THREAD

**Issue by heehminh** [UPbrella/UPbrella_back#252]
## 📝TODO
<img width="400" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76530562/faf7522f-1b8d-49a6-acdc-a35c746e97ea">

- api 명세서에는 storeId를 80으로 api 요청했을 때 해당 데이터가 보여야하는데 postman에서는 존재하지 않는 협업 지점 고유번호라고 뜹니다. <br /> 
- 데이터로 넣으신 classificationName 이 깨지는 것 같습니다.

**Comment by birdieHyun** [comment]
- API 명세서를 테스트 코드를 통해서 작성하고 있는데, 이때 storeId 값이 랜덤으로 들어가서 80에 해당하는 협업지점 고유번호가 없을 수 있습니다. 
- classificationName 수정해서 다음 배포때 반영하겠습니다.

**Comment by acceptor-gyu** [comment]
- 위 문서에서 storeId 80은 단순히 예시일 뿐 데이터베이스에 존재하지 않는 지점이라서 에러가 발생합니다.
- 데이터가 깨지는 문제는 테스트 객체를 만들어주는 라이브러리를 사용하면서 인코딩 문제가 발생한 것같습니다.


- 존재하는 지점을 조회한다면 아래와 같이 잘 나옵니다.
<img width="406" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/71162390/f929f1ae-d514-4a62-adcc-24a71d5571fd">

확인되시면 해당 이슈 닫아주시면 감사하겠습니다.
