### ISSUE TITLE
어드민 > 대여, 반납 조회 API (수정에 대한 의견)

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#253]
## API
[우산 대여 기록 조회](http://upbrella-dev.site:8080/docs/index.html#_%EC%9A%B0%EC%82%B0_%EB%8C%80%EC%97%AC_%EA%B8%B0%EB%A1%9D_%EC%A1%B0%ED%9A%8C)
`GET /admin/rent/histories?refunded=true&page=0&size=5 HTTP/1.1`

## 문제
`refund` 파라미터 없이 조회 (전체) -> `보증금 환급 여부`로 정렬이 됨 (미완료 ~~~~~~ , 완료 ~~~~~~)
해당 상태 (보증금 환급 여부) 변경 시, 변경한 기록 다른 페이지로 이동

## 의견
`대여날짜`를 기본정렬로 조회하면 해당 이슈 해결기대

## Detail
대여, 반납 현황 조회할 때 (보증금 환급 여부 필터는 전체), 보증금 환급 여부로 정렬이 되어서 데이터가 오는 것 같습니다. 

![image](https://github.com/UPbrella/UPbrella_back/assets/76439533/efeecfa5-124c-47a8-9521-fb0a64857f2d)

이렇게 되면 관리자가 보증금 환급 여부 변경 시에, 데이터가 다른 페이지로 넘어가는 이슈가 있는 것 같아요 !
조회는 대여 날짜를 기준으로 정렬해주시면 좋을 것 같은데 어떻게 생각하시나요?

**Comment by birdieHyun** [comment]
이 부분은 보증금 환급 여부를 기준으로 정렬해달라고 기획쪽에서 의견을 주신 부분인데, 회의때 다시 얘기해보면 좋을 것 같아요!

**Comment by Gwonwoo-Nam** [comment]
듣고보니 저도 대여날짜로만 정렬 & 페이징해서 드리는게 나은거같습니다!
