### ISSUE TITLE
Subclassification id와 storeList의 Subclassification 불일치 문제

### ISSUE THREAD

**Issue by chaeyeon-yang** [UPbrella/UPbrella_back#257]
## Problem

- 협업 지점 소개페이지에서 소분류 태그를 불러옵니다

<img width="1008" alt="스크린샷 2023-09-13 오전 11 27 40" src="https://github.com/UPbrella/UPbrella_back/assets/69382168/43cee647-a1f9-472a-b610-e00dfaabee7b">

- 또한 협업 지점 소개페이지에서 소분류 태그별 협업지점 목록을 보내주시는데 subclassification id가 일치하지 않아 문의드립니다.
<img width="983" alt="스크린샷 2023-09-13 오전 11 27 45" src="https://github.com/UPbrella/UPbrella_back/assets/69382168/3fdc5be1-651b-42af-ab16-28fde254f3b4">

**Comment by acceptor-gyu** [comment]
http request 데이터가 있다면 어떤 데이터와 함께 어떤 요청을 보냈는지 같이 적어주셔야 저희가 확인하기 빠를 것같은데 같이 적어주실 수 있나요?

**Comment by chaeyeon-yang** [comment]
> http request 데이터가 있다면 어떤 데이터와 함께 어떤 요청을 보냈는지 같이 적어주셔야 저희가 확인하기 빠를 것같은데 같이 적어주실 수 있나요?

위에 쓴 두 개의 api 모두 조회(get) api 이고 소분류 태그를 클릭하면 전체 협업지점 목록중에 해당 소분류 태그 제목에 해당하는 협업지점 목록이 맨 위로 스크롤 되는 형식인데 소분류 태그 제목이 아닌 id 로 보내주셔서 소분류 태그 id와 협업지점 소분류 태그 별 협업지점 목록의 소분류 태그 id가 일치하면 소분류 태그에서 보내주시는 소분류 제목을  ui에 표시하기 위해 위해 확인해봤는데 일치하지 않아서 문의 드립니다

아니면 소분류별 협업지점 목록에서 subClassification Id가 아닌 subClassification의 name을 보내주셔도 좋을 것 같습니다.

<img width="816" alt="스크린샷 2023-09-13 오후 12 09 58" src="https://github.com/UPbrella/UPbrella_back/assets/69382168/4be2fa94-f267-4141-9bb9-25943a83fb30">

**Comment by birdieHyun** [comment]
채연님 협업지점 소개 페이지에서 소분류 태그를 불러오실때, /stores/classifications 로 호출하신거 맞나요? 보여주신 사진에서는 subClassification이 아닌 classification을 호출하신것 같아서요

**Comment by chaeyeon-yang** [comment]
> 채연님 협업지점 소개 페이지에서 소분류 태그를 불러오실때, /stores/classifications 로 호출하신거 맞나요? 보여주신 사진에서는 subClassification이 아닌 classification을 호출하신것 같아서요

잘못 호출했습니다 죄송합니다 수정해서 반영하겠습니다!
