### ISSUE TITLE
협업지점 상세조회 thumbnail 문의

### ISSUE THREAD

**Issue by chaeyeon-yang** [UPbrella/UPbrella_back#258]
## Problem
- 협업 지점 상세 조회에서 

<img width="981" alt="스크린샷 2023-09-13 오전 11 47 09" src="https://github.com/UPbrella/UPbrella_back/assets/69382168/f63a6344-3379-438c-b4b9-fe931ff72c00">

- ImageUrls 에 배열로 이미지를 보내주시는데 이 중 가장 첫번째 이미지를 썸네일로 사용하면 될까요? 썸네일 이미지 하나만 필요해서요

**Comment by acceptor-gyu** [comment]
상세 조회 화면에서 이미지를 슬라이드로 넘길 수 있어야 하지 않나요? 
그러면 이미지 배열로 필요할 것같은데 아닌가용?

**Comment by Gwonwoo-Nam** [comment]
가장 먼저 보이는 페이지 말씀하시는거라면 첫번째 이미지를 사용하시면됩니다!

**Comment by chaeyeon-yang** [comment]
> 상세 조회 화면에서 이미지를 슬라이드로 넘길 수 있어야 하지 않나요? 그러면 이미지 배열로 필요할 것같은데 아닌가용?

@acceptor-gyu 아 넘기면 다음 협업지점을 불러오는 식으로 생각하고 여쭤본건데 디자이너님께 의견 여쭤보겠습니다!

**Comment by chaeyeon-yang** [comment]
해당 협업지점의 이미지들을 보여주는 것이라는 답변이 와서 그대로 사용하겠습니다.
