### ISSUE TITLE
로그인 유저 정보 조회 500 에러 

### ISSUE THREAD

**Issue by heehminh** [UPbrella/UPbrella_back#263]
## 📝TODO
<img width="639" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76530562/4a25a3c2-2f19-423b-90fd-b0dfca361667"> <br /> 

로그인 유저 정보 조회 (/users/loggedIn) 에서 500 에러 납니다!

<img width="584" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76530562/620cbf9f-90ad-47c3-a871-d15dab866293">

**Comment by birdieHyun** [comment]
로컬에서 테스트 했을땐 어디서 에러나는지 찾지를 못했어요 
추측되는 상황이 로그인 유지가 안되는 경우 에러가 날 수 있더라구요 
그래서 그 부분 예외처리 한 후 오늘중으로 배포하겠습니다.

**Comment by heehminh** [comment]
@birdieHyun 
네 알겠습니다!
