### ISSUE TITLE
협업 지점 상세페이지 

### ISSUE THREAD

**Issue by chaeyeon-yang** [UPbrella/UPbrella_back#265]
## 📝TODO

- 소분류 태그별 협업 지점 목록을 보내주시는데

<img width="1136" alt="스크린샷 2023-09-14 오전 10 32 49" src="https://github.com/UPbrella/UPbrella_back/assets/69382168/186f94c5-612d-4d43-8835-5865e5146fa5">

- 해당 storeId에 해당하는 협업지점 상세조회를 진행하는데 404에러가 뜨는데, 혹시 협업 지점 목록의 데이터가 협업지점 상세조회 테스트 데이터에 없나요?

**Comment by birdieHyun** [comment]
확인해보겠습니다!

**Comment by birdieHyun** [comment]
조회할 때 사용한 api가 /stores/introductions 인가요?

**Comment by chaeyeon-yang** [comment]
> 조회할 때 사용한 api가 /stores/introductions 인가요?

소분류 태그별 협업지점 목록을 협업지점 소개 페이지 api 로 받습니다 (GET /stores/introductions)

<img width="591" alt="스크린샷 2023-09-14 오전 11 38 24" src="https://github.com/UPbrella/UPbrella_back/assets/69382168/fee04493-6ae1-4de3-bb78-39b4f54eeb8c">

그리고 조회된 지점 클릭 시 해당 지점 id를 협업지점 상세조회 api로 넘겨서 상세정보를 요청합니다! (GET /stores/2)

<img width="682" alt="스크린샷 2023-09-14 오전 11 39 55" src="https://github.com/UPbrella/UPbrella_back/assets/69382168/51c63dba-3bf5-4138-8b98-879bf3ab6861">

**Comment by chaeyeon-yang** [comment]
아직 같은 에러가 뜨며 조회가 안되는데 수정 전인가요?

**Comment by Gwonwoo-Nam** [comment]
@chaeyeon-yang 말씀해주신 현상이 있네요 수정하겠습니다~

**Comment by Gwonwoo-Nam** [comment]
@chaeyeon-yang 배포했습니다~
