### ISSUE TITLE
어드민 > 우산관리 ETC 필드

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#280]
## API
[전체 우산 현황 조회](http://upbrella-dev.site:8080/docs/index.html#_%EC%A0%84%EC%B2%B4_%EC%9A%B0%EC%82%B0_%ED%98%84%ED%99%A9_%EC%A1%B0%ED%9A%8C)
GET /admin/umbrellas?page=0&size=5 

[우산 추가](http://upbrella-dev.site:8080/docs/index.html#_%EC%9A%B0%EC%82%B0_%EC%B6%94%EA%B0%80)
POST /admin/umbrellas

## 문제
사소한 의견이라서 남깁니다 !

우산 추가 API 에는 비고에 해당하는 `etc` 필드가 있는데, 조회할 때는 없는 것 같아서요 !

```ts
GET
{
  "id" : 9598,
  "storeMetaId" : 10,
  "uuid" : 6,
  "rentable" : false
}

POST
{
  "storeMetaId" : 73,
  "uuid" : 11,
  "rentable" : false,
  "etc" : "자두"
}
```

## 의견
![image](https://github.com/UPbrella/UPbrella_back/assets/76439533/33be3a59-2d41-448f-8a40-209306248ea5)
와이어프레임에도 비고 란이 있는 것처럼 보여서요!
한번 검토 가능하실까요?!

**Comment by Gwonwoo-Nam** [comment]
앗 그렇군요~ 반영하겠습니다!

**Comment by ShinChanU** [comment]
> 앗 그렇군요~ 반영하겠습니다!

감사합니다 ~!

**Comment by birdieHyun** [comment]
수정하여서 issue close 하겠습니다.
