### ISSUE TITLE
어드민 > 우산 관리 - 지점별 우산 통계 조회 (404에러)

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#281]
## API
[우산 지점 통계 조회](http://upbrella-dev.site:8080/docs/index.html#_%EC%9A%B0%EC%82%B0_%EC%A7%80%EC%A0%90_%ED%86%B5%EA%B3%84_%EC%A1%B0%ED%9A%8C)
GET /admin/umbrellas/statistics/{storeId}

## 문제
- 아래의 이미지 처럼 404 에러로 도착하는 지점별 우산 통계 조회 API 가 있습니다. 
- 제 생각에는 우산이 존재하지 않는 지점에서만 발생하는 에러처럼 보입니다.
<img width="633" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/49ad2578-2326-44c8-a713-686fac2c8cd4">
<img width="763" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/947dc99f-e45c-4a5d-98d1-2886c4b095c9">

- 반면, 우산이 있는 지점의 경우 아래처럼 200으로 잘 옵니다!
<img width="602" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/50ce75e3-5b89-4e59-ac2c-7b81e942437e">

## 의견
- 우산이 없는 지점이여도 값을 `0`이나, `null` 로 하여 조회가 정상적으로 되어야하는게 아닌가 라는 의견이 있습니다 !

- 아래는 `통계조회 API` 에서 404 에러나는 지점의 `우산 조회 API` 입니다!
<img width="765" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/171df5ae-17b4-4bf5-a3a7-a6fabe3f7ca3">

**Comment by Gwonwoo-Nam** [comment]
확인해보겠습니다!!

**Comment by Gwonwoo-Nam** [comment]
<img width="572" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/112251635/06fee5d1-f61f-4529-a2bc-cc2da2fdc805">
혹시 조회 시 ID storeMetaID로 하셨나요? 지금 db 상의 존재하지않는 협업지점으로 보내신 것 같습니다~ 3번으로 보내신것 보니 store_detail ID인것같습니다
@ShinChanU

**Comment by ShinChanU** [comment]
> <img alt="image" width="572" src="https://user-images.githubusercontent.com/112251635/268563957-06fee5d1-f61f-4529-a2bc-cc2da2fdc805.png"> 혹시 조회 시 ID storeMetaID로 하셨나요? 지금 db 상의 존재하지않는 협업지점으로 보내신 것 같습니다~ 3번으로 보내신것 보니 store_detail ID인것같습니다 @ShinChanU

넵.. storeId로 조회했었습니다 ...!!
storeMetaId랑 지점명을 같이 조회할 수 있는 API 가 있나요?!

** 아 storeMetaId 로 통일한다는 말씀이 storeDetailId는 따로 안쓰는 걸까요?

@Gwonwoo-Nam

**Comment by Gwonwoo-Nam** [comment]
@ShinChanU 넵~ 조회시에는 store 관련 데이터는 한가지 ID만 사용하도록 통일하고있습니다! 아직 테스트 오류가 생겨서 배포를 못했는데 배포 후에는 협업지점 ID가 storeMetaId로 나가니 그걸 그대로 요청에 보내주시면 될것같습니다~!

**Comment by ShinChanU** [comment]
> @ShinChanU 넵~ 조회시에는 store 관련 데이터는 한가지 ID만 사용하도록 통일하고있습니다! 아직 테스트 오류가 생겨서 배포를 못했는데 배포 후에는 협업지점 ID가 storeMetaId로 나가니 그걸 그대로 요청에 보내주시면 될것같습니다~!

정말 감사합니다 권우님 !!!!!!
