### ISSUE TITLE
어드민 > 우산 관리 - 우산 조회 (질문)

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#282]
## API
[전체 우산 현황 조회](http://upbrella-dev.site:8080/docs/index.html#_%EC%A0%84%EC%B2%B4_%EC%9A%B0%EC%82%B0_%ED%98%84%ED%99%A9_%EC%A1%B0%ED%9A%8C)
GET /admin/umbrellas
<img width="807" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/bdcade11-1719-4384-b14d-01b383fde2fa">

### 1. 대여 일련번호
- 와이어프레임는 `대여 일련번호`가 있는데 API 에는 없는 것 같아서 혹시 빠진건지 궁금해서 여쭤봅니다 ! (노션을 보니, 추가설명이 필요하다고 답변을 남기신것 같더라구요) 
<img width="1470" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/152ecd5e-ada6-49f2-ba5d-4329d437b2ad">

```tsx
{
      "id" : 9598,
      "storeMetaId" : 10,
      "uuid" : 6,
      "rentable" : false
}
```

### 2. 지점 고유 번호
<img width="1444" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/aac351d8-6042-47e7-90db-04776dcf5b23">

`storeMetaId` 가 지점 고유 번호인데, `storeMetaId`로 지점 정보(이름 등)를 가져올 수 있나요? 

저는 `storeMetaId` 가 `storeId`인줄 알고, 협업지점을 전체 불러와서 storeMetaId에 맞는 id를 찾아서 이름을 보여줄 생각이였는데, 보니까 `storeMetaId`와 `storeId` 가 다른 것 같아서요 !
다른게 맞는지, 다르다면 `현 위치` 에 해당하는 지점 정보를 어떻게 가져올 수 있는지 여쭤보고 싶습니다 !

**Comment by Gwonwoo-Nam** [comment]
1. 다시 확인해보고 반영하겠습니다~
2. 처음에 storeMeta, storeDetail ID를 별도 관리했는데 사용자 입장에서 헷갈려서 storeDetail의 ID으로 통일해서 가져가도록 하려고했으나 아직 개선이 덜된부분이 있을 수 있습니다. 협업지점 어드민에서 목록의 ID는 DB 상에서는 storeDetail ID입니다. 지금 보니 API에서 협업지점 이름을 같이 줘야할거같은데, 그부분이 누락이 된 것 같습니다~! name만 필드에 추가하면 될까요?

**Comment by ShinChanU** [comment]
조회 화면에서는 name 만 있으면 보여줄 수 있을 것 같은데, 등록이나 수정시에는 현위치 정보를 입력해야해서 지점별로 storeMetaId 가 필요할 것 같습니다. 협업 지점 리스트 조회에 storeMetaId도 있으면 가능할것 같은데 어떻게 해야할까요? 

@Gwonwoo-Nam 
 
<img width="399" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/edcdc9cf-9e45-4286-9a21-17872eeeb072">

**Comment by Gwonwoo-Nam** [comment]
@ShinChanU ID를 두가지로 관리하는게 나중에 복잡해질 여지가 많아보이는데 우산 추가, 수정, 삭제에서 storeDetailId를 기준으로 바꿔드리는건 어떨까요? storeDetailID로 통일한 후에 api 명세에서 storeId로 이름을 통일할까합니다.

**Comment by ShinChanU** [comment]
@Gwonwoo-Nam 좋은 것 같습니다 ! `storeDetailId` 이름으로 `storeId` 를 넣으면 되는 것 맞을까요?!

**Comment by Gwonwoo-Nam** [comment]
@ShinChanU 지금 API를 살펴보니 대부분이 meta ID를 기준으로 구현되어있어서 아무래도 meta ID로 통일하는것을 검토하고있습니다..! 내일 수정해보고 알려드리겠습니다 ㅠ

**Comment by ShinChanU** [comment]
아 그렇군요 알겠습니다 ! @Gwonwoo-Nam

**Comment by Gwonwoo-Nam** [comment]
@ShinChanU storeMeta ID 기준으로 통일했습니다~ 오늘 중으로 배포하겠습니다
