### ISSUE TITLE
어드민 > 상태신고/개선사항 확인 - 신고 내역 조회 (데이터가 추가되지 않음)

### ISSUE THREAD

**Issue by heehminh** [UPbrella/UPbrella_back#284]
## API
<a href="http://43.202.94.218:8080/docs/index.html#_%EC%8B%A0%EA%B3%A0_%EB%82%B4%EC%97%AD_%EC%A1%B0%ED%9A%8C%EC%9A%A9">신고 내역 조회용</a> <br />
<img width="475" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76530562/eeb152b0-61a2-464d-9810-d8927f2ebf2d">
<img width="473" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76530562/056df292-5409-4ec0-85e5-0a6eb8d8f62e">

## 문제
<img width="350" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76530562/ad386d3e-8d8e-42d7-ae0b-21d7fec4fdf0">
<img width="917" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76530562/a5f4f150-f627-46e0-bcd7-6494377d21a0"> <br />

우산 대여 신청을 했는데 신고 내역 조회용 api 에는 반영되지 않는 이슈가 있습니다. 대여, 반납 현황 조회 테이블을 확인해봤을 때 해당 대여 신청이 반영은 되었는데 신고 내역 조회용 api 에는 이 내용이 추가가 안되었네요!

## 의견
url 에는 status 라고 쓰셨는데, response 에서는 conditionReports 로 쓰신걸보아 여기서 충돌이 있지 않았나 싶습니다!

**Comment by birdieHyun** [comment]
확인해보겠습니다!

**Comment by birdieHyun** [comment]
수정 완료하여서 issue close 하겠습니다! 
배포 후 slack 에서 말씀드리겠습니다.
