### ISSUE TITLE
어드민 > 상태신고/개선사항 확인 - 관리자 비고 입력 api 누락

### ISSUE THREAD

**Issue by heehminh** [UPbrella/UPbrella_back#287]
## 문제
<img width="917" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76530562/43b61d93-e1b9-45a0-b8f0-a4016c851336">

## 의견
와이어프레임에 보면 4. 비고 (etc) 가 관리자가 메모하는 공간이라고 나와있는데 관리자가 작성했을 때 저장해서 반영되는 api 가 누락된 것 같습니다

**Comment by birdieHyun** [comment]
추가하겠습니다!

**Comment by heehminh** [comment]
@birdieHyun 감사합니다!!

**Comment by heehminh** [comment]
@birdieHyun 소현님이 이 기능 없어도 될 것 같다고 하셔서 이슈 닫겠습니다!
