### ISSUE TITLE
대분류 태그별 협업 지점 목록

### ISSUE THREAD

**Issue by chaeyeon-yang** [UPbrella/UPbrella_back#290]
## API

대분류 태그 별 협업 지점 목록
/stores/classification/221 500 (Internal Server Error)

<img width="724" alt="스크린샷 2023-09-18 오후 8 27 11" src="https://github.com/UPbrella/UPbrella_back/assets/69382168/cf906071-7753-4c27-a2d5-a135b3f7278d">

## 문제

500 에러가 나서 조회가 안됩니다!

**Comment by birdieHyun** [comment]
확인해보겠습니다

**Comment by birdieHyun** [comment]
수정완료하였습니다. 배포 후 다시 말씀드리겠습니다.

**Comment by chaeyeon-yang** [comment]
아직 안됩니다!

**Comment by birdieHyun** [comment]
@chaeyeon-yang 
현재 수정중입니다. 수정 완료되면 말씀드리겠습니다

**Comment by birdieHyun** [comment]
배포되었습니다
