### ISSUE TITLE
회원API - 로그인유저정보조회 이메일 정보가 포함되어있지않습니다.

### ISSUE THREAD

**Issue by LeeJSYS** [UPbrella/UPbrella_back#293]
## API
[로그인 유저 정보 조회](http://43.202.94.218:8080/docs/index.html#_%EB%A1%9C%EA%B7%B8%EC%9D%B8_%EC%9C%A0%EC%A0%80_%EC%A0%95%EB%B3%B4_%EC%A1%B0%ED%9A%8C)
GET /users/loggedIn

## 문제
- 마이페이지의 개인정보조회 페이지에서 이메일 필드가 추가되었는데 사용자의 이메일 정보를 받아올 수 있을만한 api가 없습니다.
- 현재로서는 사용할수 있을 만한 api가  [유저 목록 조회](http://43.202.94.218:8080/docs/index.html#_%EC%9C%A0%EC%A0%80_%EB%AA%A9%EB%A1%9D_%EC%A1%B0%ED%9A%8C) 가 있는데 이 api에서 모든 사용자 정보에서 사용자의 id로 이메일을 찾아서 써야하는데, 불편함이 있을 것 같습니다.

<img width="596" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/120862683/81469d99-f36d-4c97-9942-ea9ff9bc4656">
<img width="1034" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/120862683/b34f1613-0bf8-48ee-80a9-4008e603d4ed">

## 의견
-  로그인유저정보조회 Api의 응답에 사용자의 이메일 정보가 포함되면 좋을 것 같습니다.

**Comment by Gwonwoo-Nam** [comment]
앗~~ 이메일 추가하면서 마이페이지쪽에서는 누락되었군요 수정하겠습니다!
@LeeJSYS

**Comment by LeeJSYS** [comment]
@Gwonwoo-Nam 
항상 감사드립니다:)

**Comment by birdieHyun** [comment]
수정완료하였습니다. 배포 후 다시 말씀드리겠습니다.
