### ISSUE TITLE
협업 지점 상세 조회

### ISSUE THREAD

**Issue by chaeyeon-yang** [UPbrella/UPbrella_back#299]
## API
<img width="915" alt="스크린샷 2023-09-19 오후 3 14 11" src="https://github.com/UPbrella/UPbrella_back/assets/69382168/5ae05138-da9c-4794-a4fb-ef081fd7e2b5">

<img width="971" alt="스크린샷 2023-09-19 오후 3 15 54" src="https://github.com/UPbrella/UPbrella_back/assets/69382168/4a7cc8d1-37e8-4b3d-be60-ba7752fcd99b">

## 문제

- 이 중 nullable 인 속성은 아예 없는게 맞나요?

**Comment by birdieHyun** [comment]
없습니다!

**Comment by chaeyeon-yang** [comment]
<img width="926" alt="스크린샷 2023-09-19 오후 3 22 53" src="https://github.com/UPbrella/UPbrella_back/assets/69382168/8c2d71dd-7a8d-4e77-a1f1-4d23c5e851a9">

관리자자 페이지에서 해당 값들은 nullable 인 것 같은데 확인부탁드립니다!

**Comment by birdieHyun** [comment]
password만 nullable 이고 나머지는 not null이 맞습니다. 
비밀번호는 자물쇠 없는 지점일 수 있어서 nullable이지만, 다른 정보는 협업지점 등록 시 필수적인 정보라, 백엔드에서 예외처리를 하려고 하거든요. 이 부분은 회의때 더 자세히 얘기하면 좋을것 같습니다.

**Comment by birdieHyun** [comment]
그리고 이슈 등록하실때 assignee 지정 부탁드려요

**Comment by chaeyeon-yang** [comment]
기획 와이어프레임에서는 일부 값들이 nullable 인 것 같습니다

<img width="408" alt="와이어프레임" src="https://github.com/UPbrella/UPbrella_back/assets/69382168/896c3b6d-97b1-4a0b-889f-abc42e9c8280">

그래서 지금 관리자 화면에서 필수항목 표시가 안되어있는 것 같은데 기능은 다르게 구현되어 있는 것 같아서 확인 부탁드립니다.

https://www.figma.com/file/NpJqoBoBVwOs1lrKAePP95/%ED%98%91%EC%97%85%EC%A7%80%EC%A0%90-%EA%B4%80%EB%A6%AC-%EC%96%B4%EB%93%9C%EB%AF%BC?type=design&node-id=8-80&mode=design&t=HcqK9R3797Agy8A2-0

**Comment by heehminh** [comment]
항목옆에 * 인 값만 필수값인 것 같습니다 

<a href="http://43.202.94.218:8080/docs/index.html#_%ED%98%91%EC%97%85_%EC%A7%80%EC%A0%90_%EB%93%B1%EB%A1%9D">[POST] 협업 지점 등록 API</a>  에서 확인해보면 
contactNumber, instagramId 등등 Optional 을 포함한 모든 값이 필수값으로 설정되어있습니다

연세대학교 학생회관이나 카페여도 인스타 안하는 경우가 있기 때문에 이 값들은 Optional 이 맞는 것 같아요
기획회의했을 때도 인스타 없는 경우엔 해당 줄은 안보여주는 걸로 논의했던 걸로 기억합니다!

**Comment by birdieHyun** [comment]
지금 기능상으로 안되는 부분이 어디인건가요? 명세서만 수정하면 될까요?

**Comment by chaeyeon-yang** [comment]
> 지금 기능상으로 안되는 부분이 어디인건가요? 명세서만 수정하면 될까요?

안되는 부분은 없습니다! nullable인 값은 화면 딴에서 따로 처리 해줘야되서 여쭤봤습니다
optional 만 수정하면 될 것 같습니다

**Comment by birdieHyun** [comment]
> > 지금 기능상으로 안되는 부분이 어디인건가요? 명세서만 수정하면 될까요?
> 
> 안되는 부분은 없습니다! nullable인 값은 화면 딴에서 따로 처리 해줘야되서 여쭤봤습니다 optional 만 수정하면 될 것 같습니다

다른 기능 우선적으로 구현 후 와이어 프레임에 따라서 명세서 수정하도록 하겠습니다.

**Comment by birdieHyun** [comment]
배포 완료하였습니다
