### ISSUE TITLE
유저 권한 정보 추가 요청

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#302]
## API
[로그인 유저 정보 조회](http://upbrella-dev.site:8080/docs/index.html#_%EB%A1%9C%EA%B7%B8%EC%9D%B8_%EC%9C%A0%EC%A0%80_%EC%A0%95%EB%B3%B4_%EC%A1%B0%ED%9A%8C)
GET /users/loggedIn

## 문제
- 어드민 유저가 아닌 경우, 어드민 쪽 접근 허용을 막아야 할 것 같아서 유저 정보에 어드민인지, 일반 유저인지 정보를 담아서 보내주실 수 있나 싶어서 요청드립니다 !
- 또한 어드민의 경우 헤더에 어드민 메뉴도 넣으면 접근이 더 용이할 것 같기도 해서 요청합니다 !

**Comment by birdieHyun** [comment]
수정하겠습니다!

**Comment by birdieHyun** [comment]
배포 완료되었습니다.
