### ISSUE TITLE
대여폼 > 상태신고 - 최대 글자수

### ISSUE THREAD

**Issue by heehminh** [UPbrella/UPbrella_back#314]
## API
<a href="http://43.202.94.218:8080/docs/index.html#_%EC%9A%B0%EC%82%B0_%EB%8C%80%EC%97%AC_%EC%8B%A0%EC%B2%AD">[POST] 우산 대여 신청</a>

## 문제
대여폼에서 상태신고란에 400 글자 조금 넘게 작성해보았는데 다음과 같이 500 에러가 났습니다.

<img width="399" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76530562/bdf41c87-907a-4e94-ad63-0f4d3fb4fd44">

직후에 30 글자 정도 작성해보았을 땐 정상적으로 대여가 됩니다.

**Comment by birdieHyun** [comment]
확인해보겠습니다!

**Comment by heehminh** [comment]
네 감사합니다!

@birdieHyun

**Comment by acceptor-gyu** [comment]
@heehminh 글자 수 제한을 정하고 프론트에서도 placeholder로 "n 자 이내로 작성해주세요" 같이 보여주고 정하면 괜찮을 것같은데 몇 자로 하는게 좋을까요?

**Comment by heehminh** [comment]
제가 소현님께 여쭤보고 다시 답글 드리겠습니다!

@acceptor-gyu

**Comment by heehminh** [comment]
400자로 하면 될 것 같습니다! 

@acceptor-gyu
