### ISSUE TITLE
어드민 > 협업지점 이미지 추가 500 에러

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#317]
## API
[협업지점의 이미지 업로드](http://upbrella-dev.site:8080/docs/index.html#_%ED%98%91%EC%97%85%EC%A7%80%EC%A0%90%EC%9D%98_%EC%9D%B4%EB%AF%B8%EC%A7%80_%EC%97%85%EB%A1%9C%EB%93%9C)

![image](https://github.com/UPbrella/UPbrella_back/assets/76439533/61d5bc7a-4861-4731-8957-472e2a38007a)

## 문제
- 협업 지점 이미지의 추가가 되지 않는 것 같은데 한번 확인해주실 수 있나요?

<img width="1501" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/ab6183b8-3da2-4e01-9f3c-de45f79ed1f8">

**Comment by birdieHyun** [comment]
확인해보겠습니다!
