### ISSUE TITLE
공통 > 저장시간 타임존 이슈

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#328]
## API
날짜, 시간 관련 데이터 API 공통 

ex. 
[우산 대여 기록 조회](http://upbrella-dev.site:8080/docs/index.html#_%EC%9A%B0%EC%82%B0_%EB%8C%80%EC%97%AC_%EA%B8%B0%EB%A1%9D_%EC%A1%B0%ED%9A%8C)
[사용자 대여 내역 조회](http://upbrella-dev.site:8080/docs/index.html#_%EC%82%AC%EC%9A%A9%EC%9E%90_%EB%8C%80%EC%97%AC_%EB%82%B4%EC%97%AD_%EC%A1%B0%ED%9A%8C)

## 문제
아직 날짜 데이터가 KST가 아닌 UTC 로 되어있는 것 같습니다 ~!
<img width="557" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/1eded0a7-75d5-4bf7-88d0-804b131d409f">
(2023-10-08 15:17 에 저장한 데이터)

- 해당 이슈는 지점 영업 시간 + 활성화 여부에도 영향을 주는 것으로 보입니다 !

**Comment by birdieHyun** [comment]
확인해보겠습니다!

**Comment by birdieHyun** [comment]
시간 변경했습니다!
