### ISSUE TITLE
어드민 > 협업지점 관리 - 이미지 업로드 500 에러

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#329]
## API
[협업지점의 이미지 업로드](http://upbrella-dev.site:8080/docs/index.html#_%ED%98%91%EC%97%85%EC%A7%80%EC%A0%90%EC%9D%98_%EC%9D%B4%EB%AF%B8%EC%A7%80_%EC%97%85%EB%A1%9C%EB%93%9C)

## 문제
- 업로드하는 이미지의 크기가 1MB 이상인 파일은 500 Error 가 나옵니다.
<img width="572" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/509e6613-b5b1-43a8-8f4c-719afee80458">

## 의견
- 혹시 이미지 업로드 용량 정책이 있을까요 ?
- 일단 현상을 발견하고 이미지의 크기가 1MB 이상인 파일을 업로드하면 프론트 단에서 에러 메세지를 띄워주고 있는데, 현행을 유지하면 될까요?

<img width="1085" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/70d569d9-7d19-4430-bbac-0319638e5731">
(네트워크 요청 X)

**Comment by birdieHyun** [comment]
확인해보겠습니다!

**Comment by birdieHyun** [comment]
기본 설정이 1MB로 되어있었습니다. 10MB로 변경 했습니다! 
배포 후 말씀드리겠습니다.

**Comment by birdieHyun** [comment]
배포 완료했습니다.
