### ISSUE TITLE
어드민 > 협업지점 조회 및 수정 - 활성화 여부 (`activateStatus`) `false`  초기화 버그

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#330]
## API
[전체 협업 지점 조회](http://upbrella-dev.site:8080/docs/index.html#_%EC%A0%84%EC%B2%B4_%ED%98%91%EC%97%85_%EC%A7%80%EC%A0%90_%EC%A1%B0%ED%9A%8C)
[협업 지점 변경](http://upbrella-dev.site:8080/docs/index.html#_%ED%98%91%EC%97%85_%EC%A7%80%EC%A0%90_%EB%B3%80%EA%B2%BD)

#### 협업 지점 조회 시에는 활성 여부가 `true`였는데, 수정하고 나면 다시 `false`로 되돌아오는 버그가 있는 것 같습니다.

id: 278 지점 
활성 여부 `true` 
<img width="1132" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/bed6ae38-6c92-4be3-9641-ed848f1d792a">

수정 후 저장
<img width="773" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/126e5842-0982-4dc4-bef1-3fefa9bae640">

활성 여부 `false` 로 조회됨
<img width="1088" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/fe75a9ae-4ebc-48f0-8d3c-8092bd83e457">

**Comment by birdieHyun** [comment]
확인해보겠습니다!

**Comment by birdieHyun** [comment]
수정했습니다! 배포 후 이슈 닫도록 하겠습니다

**Comment by birdieHyun** [comment]
배포 완료했습니다.
