### ISSUE TITLE
어드민 > 우산관리 - 우산 통계 개수와 조회되는 우산 개수가 다른 이슈

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#331]
## API
[우산 전체 통계 조회](http://upbrella-dev.site:8080/docs/index.html#_%EC%9A%B0%EC%82%B0_%EC%A0%84%EC%B2%B4_%ED%86%B5%EA%B3%84_%EC%A1%B0%ED%9A%8C)
[전체 우산 현황 조회](http://upbrella-dev.site:8080/docs/index.html#_%EC%A0%84%EC%B2%B4_%EC%9A%B0%EC%82%B0_%ED%98%84%ED%99%A9_%EC%A1%B0%ED%9A%8C)

## 문제
- 우산 전체 통계 조회에서 확인되는 우산 개수 (ex. 21개) 와 실제로 우산 현황을 조회했을 때 확인되는 우산의 개수(ex. 13개) 의 차이가 있는 것 같습니다 !

---

#### 우산 전체 통계 조회 - (totalUmbrellaCount : 21)
<img width="810" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/7ad76d96-0303-4a66-b0f5-3acac6c947bb">

---

#### 전체 우산 현황 조회 `(page: 0, size: 30)` - (list length: 13)
<img width="910" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/49a54932-4d2c-49ee-b7d5-e40396a2f73b">

<img width="794" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/bc9093a3-6300-47bc-ba6b-6048c930c145">

**Comment by birdieHyun** [comment]
확인해보겠습니다!

**Comment by birdieHyun** [comment]
기본 설정이 1MB로 되어있었습니다. 10MB로 변경 했습니다! 
배포 후 말씀드리겠습니다.

**Comment by birdieHyun** [comment]
현재 이슈로 인해 우산과 대여기록이 연동이 되지 않고 있습니다. 
우선적으로 배포 후 추후에 수정하겠습니다.

**Comment by birdieHyun** [comment]
버그 수정 후 배포하였습니다.
