### ISSUE TITLE
회원관리 admin API > 블랙리스트 등록 시에도 대여, 반납이 되는 오류

### ISSUE THREAD

**Issue by LeeJSYS** [UPbrella/UPbrella_back#334]
## API
회원관리 admin API > [회원 정지](http://43.202.94.218:8080/docs/index.html#_%ED%9A%8C%EC%9B%90_%EC%A0%95%EC%A7%80)

## 문제
블랙리스트 처리한(회원 정지) 사용자가 로그아웃하지 않은 상태라면 대여, 반납이 모두 가능합니다.
블랙리스트 처리시 대여, 반납이 불가해야 할 것 같습니다.

## Detail
<img width="1332" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/120862683/0dca7c32-ba4c-478f-8bc1-82e7b6e06cd8">

![image](https://github.com/UPbrella/UPbrella_back/assets/120862683/6cda9254-66f8-4d2b-bac2-77baf19cc6b9)

![image](https://github.com/UPbrella/UPbrella_back/assets/120862683/0f218586-9c05-42dd-97fb-1bf678f1f93e)

**Comment by birdieHyun** [comment]
배포 후 이슈 클로즈 하겠습니다!

**Comment by LeeJSYS** [comment]
네 감사합니다!
