### ISSUE TITLE
회원가입: 은행+계좌를 입력하지 않았을때 400에러

### ISSUE THREAD

**Issue by LeeJSYS** [UPbrella/UPbrella_back#341]
## API
[회원 가입](http://43.202.94.218:8080/docs/index.html#_%ED%9A%8C%EC%9B%90_%EA%B0%80%EC%9E%85)

## 문제
현재 회원가입시 은행 + 계좌번호를 넣지 않으면 회원가입 진행이 되지 않습니다.
은행+계좌번호를 정상적으로 입력되면 회원가입진행이 됩니다.

<img width="548" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/120862683/5121b36a-78cf-4d2c-80f9-44b00bbf9d41">
<img width="335" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/120862683/eb9c4a25-d64e-4812-8f38-35089869b059">

## 의견
혹시 accountnumber을 숫자만 받도록 수정하시다가 이부분이 변경된것이 아닌가 싶습니다.

**Comment by birdieHyun** [comment]
확인해보겠습니다!

**Comment by birdieHyun** [comment]
수정 완료하였습니다.

**Comment by LeeJSYS** [comment]
감사합니다!!
