### ISSUE TITLE
[QA] 우산 관리 어드민 - 요청사항 및 질문

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#350]
## API
[지점 우산 현황 조회](http://upbrella-dev.site:8080/docs/index.html#_%EC%A7%80%EC%A0%90_%EC%9A%B0%EC%82%B0_%ED%98%84%ED%99%A9_%EC%A1%B0%ED%9A%8C)
[우산 정보 수정](http://upbrella-dev.site:8080/docs/index.html#_%EC%9A%B0%EC%82%B0_%EC%A0%95%EB%B3%B4_%EC%88%98%EC%A0%95)

## 문제
[QA_notion](https://www.notion.so/heehminh/0ce313dc1fc84d1fa8e4b74834c7c00e?pvs=4)
해당 QA에서 백엔드분들의 도움이 필요한 것 같아서 요청합니다 !

1. `우산 조회` 시, 우산 `고유 번호`로 `정렬`이 가능할까요 ?? (`uuid` 를 의미하는 것 같습니다. 현재는 `id`로 정렬)
<img width="400" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/e3d86ee2-c452-4acb-9b9c-4e13382a290b">

2. `우산 수정` 시, 분실 여부(`missed`)를 `true` 로 변경해도 대여폼을 정상적으로 사용이 가능한데 올바른 흐름이맞을까요 ?? 
<img width="400" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/0063382c-3fcf-4eb7-8b5d-3939bcda7997">
<img width="400" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/9d999f0d-abf3-4b2c-b829-2f59e7cf3101">

## 의견
한번 확인해보시고 의견주시면 감사하겠습니다 !!

**Comment by birdieHyun** [comment]
1. uuid 기준으로 정렬될 수 있게 수정하겠습니다. 
2. 분실 시 대여되지 않도록 수정하겠습니다.

**Comment by ShinChanU** [comment]
감사합니다 동현님 ! @birdieHyun

**Comment by birdieHyun** [comment]
해결하였습니다! 확인해주시고 잘 해결되었으면 이슈 클로즈 부탁드려요! 
@ShinChanU

**Comment by ShinChanU** [comment]
동현님, 이제 확인 중인데요 !
우산관리번호(`uuid`)로 정렬이 아래와 같이 되는데 예상한 결과가 맞으실까요 ?
@birdieHyun 

<img width="511" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/a1e48fe3-c97d-4e1c-b7c9-63902b6838fa">

**Comment by ShinChanU** [comment]
동현님, 우산 분실여부도 질문이 있습니다 ! 현재 수정하신 내용을 보니까

1. 아래처럼 분실여부 `missed: true` 로 요청에 성공하고
<img width="622" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/a06d168f-ee7a-4ef0-9f31-d5ed9ec2357f">
<img width="619" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/63bd6bba-5c1f-4624-afa3-cfcc8aa37812">

2. 대여를 신청할 때 에러를 보여주더라구요. 대여를 할 때가 아닌, 대여폼을 조회할 때 에러를 보여주는게 더 자연스러울것 같다는 개인적인 생각이 있는데 동현님은 어떻게 생각하시나요 ?! @birdieHyun 
<img width="571" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/5ccad18d-d624-4889-bc7a-19e1abe72456">
<img width="491" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/61d7db52-428a-488a-80d9-75bfe5651ec6">
<img width="524" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/bf842955-52f5-4221-bf73-121446218d28">
<img width="558" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/beeb92d5-444e-4eb7-8130-12b4d820ae5e">

**Comment by birdieHyun** [comment]
@ShinChanU 
우산 정렬은 수정하였습니다. 

분실 우산의 경우 #362 와 중복된 이슈여서 362에서 해결하겠습니다. 

확인해주시고 이상 없으면 이슈 클로즈 부탁드립니다!
