### ISSUE TITLE
[어드민-협업지점 대분류 태그] 대분류 삭제 에러

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#360]
## API
[대분류 삭제](http://upbrella-dev.site:8080/docs/index.html#_%EB%8C%80%EB%B6%84%EB%A5%98_%EC%82%AD%EC%A0%9C)

## 문제
- 현재 협업지점에서 사용하고 있는 대분류 태그가 아닌데 삭제가 불가능한 현상이 있는 것 같습니다. 확인해주시면 감사하겠습니다 !! (테스트 - "연세대학교 학생회관" (대분류 태그 중 하나)) 

<img width="787" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/be7d9afa-cda6-4fba-92ef-ebbcf1e1c35a">
<img width="653" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/e2d3dbac-f577-4062-b67a-b77a5f265d11">
<img width="498" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/dba01c73-6c7a-434a-9bf5-79dc51098606">

**Comment by acceptor-gyu** [comment]
현재 classificationId가 222를 사용하고 있는 협업 지점이 있는 것같은데 classificationId가 558 (이슈 테스트)로 새로 만들었는데 한 번 이거로 테스트 해주시고 혹시 어떠한 협업 지점도 cassificationId 222를 사용하지 않다고 조회하는 것이라면 이에 대해서도 한 번 확인해주시면 감사하겠습니다.

**Comment by acceptor-gyu** [comment]
PR close에 의해 auto close가 되어서 reopen 했습니다.

**Comment by ShinChanU** [comment]
222번이 사라져서 222번으로는 테스트를 해보지 못했지만, 다른 것들은 잘 삭제되는 것 같아서 이슈 닫겠습니다 감사합니다 !!
