### ISSUE TITLE
storeId=1에 해당 하는 협업지점이 반납폼에서 뜨지 않습니다

### ISSUE THREAD

**Issue by heehminh** [UPbrella/UPbrella_back#361]
## 문제
storeId = 1에 해당하는 협업지점이 없는 걸로 뜨는데 

<img width="1072" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76530562/3e314bd3-78c7-4a1d-9a73-207dab1bb55f">

어드민 협업 지점 관리에는 storeId=1이 있어서 이 부분 한 번 확인해주세요! 

<img width="1071" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76530562/1733e0ab-d133-464b-9129-5b1fd20e607a">

**Comment by acceptor-gyu** [comment]
storeId = 1인 협업 지점은 존재합니다.
+ `GET /return/form/1` 요청 시 에러가 발생하는 것은 협업 지점이 존재하지 않다고 에러가 발생하는 것이 아닌 Internal Server Error(이 부분에 대해서 예외 반환 추가하겠습니다.)가 발생하는데 그 이유는 제 생각에 현재 storeId = 1인 협업 지점은 비밀번호가 필요한 협업 지점입니다. 따라서 query parameter로 salt와 signature가 필요한데 그 부분이 없기 때문에 발생하는 에러인 것같습니다.

**Comment by heehminh** [comment]
@acceptor-gyu 

아하 알겠습니다! 

<img width="614" alt="스크린샷 2023-11-08 오후 2 47 36" src="https://github.com/UPbrella/UPbrella_back/assets/76530562/2a773adf-aef3-4306-a036-10e13b36660c">

우산대여신청 API에서 Request fields에는 salt, signature가 없는데 이것들도 추가로 보내주면 될까요? 아니면 url에 쿼리스트링으로 적어주기만 하면 될까요??

**Comment by acceptor-gyu** [comment]
쿼리 스트링으로 해주시면 됩니다. 이 부분도 문서에 추가하겠습니다.

**Comment by acceptor-gyu** [comment]
<img width="998" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/71162390/877d6467-48f6-47a7-a2fe-1d9675e3ec8b">
API 문서에는 추가되어있었는데 배포가 안되어있는 줄 알았는데 이미 되어있는 것같습니다.

**Comment by heehminh** [comment]
@acceptor-gyu 

아하! 반납 폼 데이터 조회 api 였군요!! 감사합니다!
