### ISSUE TITLE
대여폼 > 상태신고란 400자 오류 

### ISSUE THREAD

**Issue by heehminh** [UPbrella/UPbrella_back#368]
## API
<a href="http://43.202.94.218:8080/docs/index.html#_%EC%9A%B0%EC%82%B0_%EB%8C%80%EC%97%AC_%EC%8B%A0%EC%B2%AD">우산 대여 신청 API</a>

<a href="https://www.notion.so/heehminh/QA-59ad3ea34b1942aabf6df92880e5b083?p=0583e51230264a329f6cc618c84a2be6&pm=s">QA - 대여폼 상태신고란 오류</a>

## 문제
대여폼 내 상태신고란 1) 400자 딱 맞추거나 2)유저가 조금 넘게 글을 작성하면 400자 제한이 걸리긴 하는데 오류가 뜬다고 합니다. 

## 의견
최대 글자수를 400자 조금 이상으로 설정해주시면 될 것 같습니다. 아마도 반납폼에서도 동일한 증상이 나타났을 것 같습니다!

**Comment by birdieHyun** [comment]
400자까지 대여가 가능하고 401자부터 예외가 발생하도록 되어있는데, 딱 맞춰서 예외처리를 하는 것이 아닌, 여유롭게 450자로 예외처리를 하는 것을 원하시는걸까요? 

@heehminh

**Comment by heehminh** [comment]
@birdieHyun 

지금 딱 400자 작성하면 에러난다고 하셔서 확인해주시고 에러만 안나게 하면 될것같아용!

**Comment by birdieHyun** [comment]
수정 완료하였습니다.

확인해보시고 해결되었으면 이슈 클로즈 부탁드려요! 
@heehminh

**Comment by heehminh** [comment]
@birdieHyun 
잘 동작합니다! 감사합니다 :)
