### ISSUE TITLE
Release API Cors 문제

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#374]
## API
공통

## 문제
아직 해결이 되지 않은 것 같아서 이슈 남겨놓겠습니다 !

`Release` 환경에서만 `CORS`, `301`, `403` 응답이 불규칙적으로 반환이 되는 현상이 있습니다.
`Release` 서버
<img width="1223" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/980c985a-d568-429d-b6fb-16901a85c707">

반면, `Release-Dev` 서버는 정상적인 API를 반환합니다.
<img width="1503" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/839a6252-2aba-40fa-b69b-a5d57d1d84de">

프론트 코드는 `release-dev`와 `release` 같은 브랜치 버전이며, 최근 배포는 2주전입니다.
<img width="985" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/29d1d44d-2720-499c-9231-1e4456044a36">
<img width="794" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/8fbe014d-4cec-46a7-b023-c60bd802e46d">

혹시나 해결이나, 도움을 드릴 수 있을 까 싶어서 프론트쪽 코드에 문제가 있는지 테스트하고 살펴보고 있는데, 알기가 어려워서 이렇게 이슈로 남겨둡니다 ..ㅜ! 백엔드 분들도 어려우시겠지만 한번 해결방법을 고민해주시면 감사하겠습니다.

**Comment by maxswjeon** [comment]
결국 CORS는 헤더로 관리되는데, 코드가 동일한데 작동하지 않는다면 Release 쪽에 연결된 ALB를 확인해야 할 거 같습니다. 또한 CORS 헤더가 2번 전송되면 위와 같은 오류가 발생할 수 있는데, 이것도 한번 확인을 해 주시는게 좋을 거 같습니다.
401/403 떴을 때 Received Header를 확인하는게 급선무일 듯 합니다

**Comment by birdieHyun** [comment]
확인해보고 최대한 빠르게 조치하겠습니다!

**Comment by birdieHyun** [comment]
@ShinChanU 
해결 완료해서 이슈 클로즈 하겠습니다. 
ECS가 정상 작동하지 않아서 발생한 문제같습니다.

**Comment by ShinChanU** [comment]
잘 되네요 감사합니다 !!
@birdieHyun
