### ISSUE TITLE
반납폼 데이터 조회  > storeId에 반납지점 번호가 오는 현상

### ISSUE THREAD

**Issue by heehminh** [UPbrella/UPbrella_back#379]
## API
<a href="http://43.202.94.218:8080/docs/index.html#_%EB%B0%98%EB%82%A9_%ED%8F%BC_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%A1%B0%ED%9A%8C">반납폼 데이터 API</a>

http://43.202.94.218:8080/return/form/290?salt=533035&signature=B107BDC948FFFAB87CEBFD829D2D6053F86646C9E7E1B6715A2C46468FE62B88

## 문제
<img width="547" alt="스크린샷 2023-12-04 오후 7 50 58" src="https://github.com/UPbrella/UPbrella_back/assets/76530562/b380c511-53b3-41d3-b5e2-7e5b07db099e">

storeId 에 대여지점 번호가 아닌 반납지점 번호가 오고 있습니다.

명세에는 대여지점 번호로 명시되어 있습니다.
<img width="677" alt="스크린샷 2023-12-04 오후 7 51 41" src="https://github.com/UPbrella/UPbrella_back/assets/76530562/c163bd22-6f9c-41e8-894c-95862d804b81">

**Comment by birdieHyun** [comment]
반납 시 대여 지점 번호가 필요한 것이 아닌, 반납 지점 ID가 필요한거 아닌가요? 
명세서가 잘못 기입된 거라서 명세서 수정하겠습니다
@heehminh

**Comment by heehminh** [comment]
@birdieHyun 

rentStoreName에 제가 직전에 대여한 지점명이 오는 것 같은데 맞나요? storeId에 맞는 반납할 지점명이 와야하는것 아닌가요?!

**Comment by birdieHyun** [comment]
http://43.202.94.218:8080/return/form/290?salt=533035&signature=B107BDC948FFFAB87CEBFD829D2D6053F86646C9E7E1B6715A2C46468FE62B88

이렇게 요청 보냈을 때, 응답으로 storeId가 290이 오면 제대로된 응답이 아닌건가요?
상황을 조금 더 자세히 설명해주실 수 있으신가요? 

@heehminh
