### ISSUE TITLE
어드민 > 보관함 수정 API 오류

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#380]
## API
[보관함 수정](http://upbrella-dev.site:8080/docs/index.html#_%EB%B3%B4%EA%B4%80%ED%95%A8_%EC%88%98%EC%A0%95)

## 문제
- 수정상황 : storeId 이전 값 그대로, secretKey만 변경

보관함을 수정할 때, 협업 지점(storeId)을 그대로 두고, 비밀키(secretKey)만 변경해서 `patch` api 를 보냈는데 400 에러가 나옵니다 ..!!

<img width="756" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/46a11a15-6381-4ca8-800d-50cc2518a177">

<img width="769" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/b0805526-c07f-4114-9a13-311044068e20">

## 의견
추가(post) api의 에러 핸들링 로직이 patch 때도 똑같이 작동하는건 아닌지 라는 생각이 있습니다 !

 한번 확인해주시면 감사하겠습니다 ~!

**Comment by birdieHyun** [comment]
확인해보겠습니다!

**Comment by birdieHyun** [comment]
수정 완료하였습니다! 
확인 후 이상 없으면 이슈 클로즈 해주시면 감사하겠습니다 😄

**Comment by ShinChanU** [comment]
잘되네요 감사합니다 동현님 !!
@birdieHyun
