### ISSUE TITLE
어드민 > 협업지점 리스트 조회 오류

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#400]
## API
[협업 지점 관리 Admin API](http://upbrella-dev.site:8080/docs/index.html#Store-Admin-API)

## 문제
어드민 > 협업지점 전체 조회 시에, dev 서버랑, release 서버에서 같은 데이터가 조회 되는 버그가 있는 것 같습니다. 

1. 
<img width="1662" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/65d1ef12-740c-468f-b97c-fe4e7ded3c4b">
좌 (dev server), 우 (release server) (같은 데이터 응답 -release )

---
2. dev 서버에서 데이터 추가 (이때는 dev 서버의 정상적인 데이터가 옵니다)
<img width="1652" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/f3e9d382-915d-479b-a465-e035d775e6bd">
좌 (dev server), 우 (release server) (다른 데이터 응답)

---
3. release 서버 다시 새로고침  - 같은 응답으로 변경 (dev)
<img width="1598" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/36a8a1ee-6366-4d00-b92f-e17cd3812276">
좌 (dev server), 우 (release server) (같은 데이터 응답 - ㅇev)

## 의견
가장 최근에 수정한 DB를 응답으로 오는게 아닌지라는 생각이 있습니다 !

**Comment by birdieHyun** [comment]
현재 캐싱 서버가 prod 와 dev 모두 연결되어 있어서 에러가 발생하는것 같습니다! 
수정하겠습니다!

**Comment by birdieHyun** [comment]
수정 완료해서 이슈 클로즈 하겠습니다!
