### ISSUE TITLE
블랙리스트 > 회원가입 문구 수정 요청

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#401]
## API
[회원 가입](http://upbrella-dev.site:8080/docs/index.html#_%ED%9A%8C%EC%9B%90_%EA%B0%80%EC%9E%85)

## 문제
- 블랙리스트 당한 유저가 회원가입을 하면 500에러가 나오는데, 구체적으로 변경해주실 수 있을까요 ?
<img width="1631" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/bef358d7-572f-4868-b4f1-dcdd3c71fd73">

## 의견
프론트 단에서 500 에러일때, 문구를 설정하면 되긴하는데, 뭔가 껄끄러운 느낌이라 요청 드려요 !

`서비스 접근이 불가한 유저입니다.` 라는 문구였으면 좋겠습니다 !

**Comment by birdieHyun** [comment]
네 수정하겠습니다!

**Comment by birdieHyun** [comment]
수정 완료해서 이슈 클로즈 하겠습니다!
