### ISSUE TITLE
우산 반납 시 > 우산 위치 변경 오류

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#405]
## API
[우산 반납 신청](http://upbrella-dev.site:8080/docs/index.html#_%EC%9A%B0%EC%82%B0_%EB%B0%98%EB%82%A9_%EC%8B%A0%EC%B2%AD)
[전체 우산 현황 조회](http://upbrella-dev.site:8080/docs/index.html#_%EC%A0%84%EC%B2%B4_%EC%9A%B0%EC%82%B0_%ED%98%84%ED%99%A9_%EC%A1%B0%ED%9A%8C)
[지점 우산 현황 조회](http://upbrella-dev.site:8080/docs/index.html#_%EC%A7%80%EC%A0%90_%EC%9A%B0%EC%82%B0_%ED%98%84%ED%99%A9_%EC%A1%B0%ED%9A%8C)

## 문제
우산 대여 후, 반납을 하고 나서 반납 위치가 우산에 반영되지 않는 문제가 있는 것 같습니다 .. !!

우산 번호 : 123

1. 대여
대여 위치 : 283 (에이투지)
<img width="832" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/572a2c43-4d70-4446-8a97-04a2244381ed">

---

2. 반납
반납 위치 : 281 (모티브)
<img width="764" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/cd9669e2-2aea-4c7b-8007-45e733121965">

---

3. 우산 관리에서 우산위치 확인
우산 위치:  283 (에이투지) (모티브로 변경되지 않았음)
<img width="795" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/51229297-4c72-4ff7-bb47-55fa3c5afda2">

---

** 4.  근데 지점 필터로 했을 때는 또 나오지 않네요
<img width="836" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/167de7f7-aef0-4036-99b7-488fabf42310">

**Comment by birdieHyun** [comment]
확인해보겠습니다!

**Comment by birdieHyun** [comment]
수정 후 배포 완료하였습니다.
