### ISSUE TITLE
우산 대여 > 500 에러

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#406]
## API
[우산 대여 신청](http://upbrella-dev.site:8080/docs/index.html#_%EC%9A%B0%EC%82%B0_%EB%8C%80%EC%97%AC_%EC%8B%A0%EC%B2%AD)

## 문제
dev 서버에서 테스트 중에, 우산 대여가 되지 않는 (500 응답) 우산이 있는데 어떤 문제가 있는지 알 수 있을까요 ??

<img width="1124" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/fbe066a5-4f29-48c2-a22d-cdc4f6c63425">

<img width="546" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/2079d948-bfbb-4cfe-8a80-35f66f04e00d">

<img width="962" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/2a8665ae-02cd-4c1d-89a4-21314021f435">

## Detail
```
curl 'http://api.upbrella-dev.site/rent' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Referer: http://upbrella-dev.site/' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36' \
  -H 'Content-Type: application/json' \
  --data-raw '{"region":"신촌","storeId":282,"umbrellaId":279,"conditionReport":""}' \
  --compressed \
  --insecure
```

**Comment by birdieHyun** [comment]
확인해보겠습니다!

**Comment by birdieHyun** [comment]
로그상으로는 HTTP method 형식이 잘못되었다고 나오네요
정확한 원인을 아직 잘 모르겠는데 어떤 우산에서 발생하는지 알 수 있을까요? 

올려주신 사진상의 우산은 테스트 해보니 대여 가능해서요

@ShinChanU

**Comment by ShinChanU** [comment]
위 사진의 우산은 아니지만, 아래 링크의 우산도 같은 상황인 것 같습니다 !
혹시 보관함과 관련된 에러일까요 ? (해당 지점이 보관함 등록이 되어있긴합니다)

![image](https://github.com/UPbrella/UPbrella_back/assets/76439533/d17663a3-6dfe-4eef-acad-2a0e42d07669)

![image](https://github.com/UPbrella/UPbrella_back/assets/76439533/4fddd703-0ffa-4052-98d8-fd935f2a97e3)

http://upbrella-dev.site/rent/form/298

@birdieHyun

**Comment by birdieHyun** [comment]
확인해보니 보관함이 있는 협업지점에 있는 우산들에서 발생하는 에러같아요.
현재 보관함의 secretKey를 32자 이상으로 입력해야 하는데, 에러가 나는 보관함의 secretKey가 짧아서 발생하는 오류입니다! 

secretKey를 등록할 때 길이 제한을 추가해야 할 것 같아요.

**Comment by ShinChanU** [comment]
그렇군요 알겠습니다 !
길이 제한 추가해두겠습니다 !

@birdieHyun

**Comment by birdieHyun** [comment]
32자 최소 제한으로 배포했습니다! 
@ShinChanU
