### ISSUE TITLE
어드민 대여, 반납 현황 조회 > 보증금 입금, 환급 여부 관련 질문

### ISSUE THREAD

**Issue by ShinChanU** [UPbrella/UPbrella_back#407]
## API
[대여 환급 확인](http://upbrella-dev.site:8080/docs/index.html#_%EB%8C%80%EC%97%AC_%ED%99%98%EA%B8%89_%ED%99%95%EC%9D%B8)
[대여 지불 확인](http://upbrella-dev.site:8080/docs/index.html#_%EB%8C%80%EC%97%AC_%EC%A7%80%EB%B6%88_%ED%99%95%EC%9D%B8)

## 문제
<img width="1154" alt="image" src="https://github.com/UPbrella/UPbrella_back/assets/76439533/6f01ba08-09d6-4041-bc51-9c4bcf73cdb1">

`보증금 입금 여부` 와` 보증금 환급 여부` 가 토글 형식(true 였으면 false, false 였을 때는 true)으로 API 가 작동하는 것으로 알고 있는데, 현재 `입금 -> 미입금`, `환급 완료 -> 미완료` 로는 변경이 안 되는데 원래 그랬었을까요 .. ?! (반대 상황은 정상적으로 작동합니다.)

원래 `미확인 -> 확인` 으로 변경하는 기능만 있었는지 제가 잘 기억이 안나서 여쭤봅니다 !

**Comment by birdieHyun** [comment]
확인해보겠습니다!

**Comment by birdieHyun** [comment]
토글 형식으로 동작하도록 수정했습니다!
