### ISSUE TITLE
협업지점 CRUD 

### ISSUE THREAD

**Issue by birdieHyun** [UPbrella/UPbrella_back#55]
## 📝TODO
- [ ] 협업지점 CRUD
- [ ] 협업지점 이미지 업로드 구현
- [x] #87

**Comment by Gwonwoo-Nam** [comment]
이슈 작업 단위를 맞추기 위해 CRUD를 분리하는건 어떨까요?

**Comment by birdieHyun** [comment]
> 이슈 작업 단위를 맞추기 위해 CRUD를 분리하는건 어떨까요?

이미.... 커밋하면서 작업을 다 해버렸슴당
